apiVersion: v1
kind: Service
metadata:
  name: lbg-api
spec:
  type: LoadBalancer
  selector:
    app: lbg-api
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lbg-api
  labels:
    app: lbg-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: lbg-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: lbg-api
    spec:
      containers:
      - name: lbg-api
        image: serenainzani/lbg-api:latest
        ports:
        - containerPort: 5000
